"""initial schema

Revision ID: 352b0972431d
Revises: 
Create Date: 2026-08-27 12:38:44.996192
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = '352b0972431d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confirmation_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guest_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('table_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_reservations_idempotency_key')
    )
    op.create_index(op.f('ix_reservations_confirmation_code'), 'reservations', ['confirmation_code'], unique=True)
    op.create_index('ix_reservations_start_at', 'reservations', ['start_at'], unique=False)
    op.create_index('uq_reservations_table_slot', 'reservations', ['table_id', 'start_at'], unique=True, postgresql_where="status = 'booked'")
    op.create_table('calls',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('twilio_call_sid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('disposition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reservation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recording_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transcript_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metrics_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_twilio_call_sid'), 'calls', ['twilio_call_sid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calls_twilio_call_sid'), table_name='calls')
    op.drop_table('calls')
    op.drop_index('uq_reservations_table_slot', table_name='reservations', postgresql_where="status = 'booked'")
    op.drop_index('ix_reservations_start_at', table_name='reservations')
    op.drop_index(op.f('ix_reservations_confirmation_code'), table_name='reservations')
    op.drop_table('reservations')
    # ### end Alembic commands ###
